workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.example.videoplayer"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Set up code signing settings on Codemagic
        script: |
          echo $APP_STORE_CONNECT_PRIVATE_KEY | base64 --decode > /tmp/key.p8
      - name: Build iOS release
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
      - build/ios/ipa
    publishing:
      email:
        recipients:
          - your-email@example.com